"""User-facing strings, in English and French.

Machine-readable exports (JSON, CSV) keep a stable English schema whatever the
selected language. Everything a human reads, on the other hand, follows the
current language: interface labels, reports, TXT/Markdown/HTML exports.

The active language is process-wide. Set it once at start-up with
:func:`set_language`; :func:`detect_language` guesses it from the environment.
"""
from __future__ import annotations

import os
import warnings
from typing import Dict

EN: Dict[str, str] = {
    # header
    "app_title": "ImgMetaManager",
    "app_tagline": "Read, export, copy and remove the metadata of your images.",
    # loading
    "tab_files": "Files",
    "tab_folder": "Folder",
    "upload_label": "Drop your images here (or click to browse)",
    "folder_label": "Folder path on this machine",
    "folder_placeholder": "/home/me/Photos  •  C:\\Users\\me\\Pictures  •  /Users/me/Pictures",
    "folder_recursive": "Include sub-folders",
    "folder_scan": "Scan folder",
    "gallery_label": "Analysed images",
    "clear_all": "Remove all",
    "reload": "Re-analyse",
    # viewer
    "tab_view": "Preview and metadata",
    "preview_label": "Preview",
    "summary_label": "Summary",
    "filter_groups": "Visible groups",
    "filter_search": "Search a tag or a value",
    "filter_sensitive": "Sensitive data only",
    "table_group": "Group",
    "table_tag": "Tag",
    "table_value": "Value",
    "copy_section": "Copy items",
    "copy_hint": "Click a table row to add it here, then use the copy icon.",
    "copy_style": "Layout",
    "copy_add_all": "Add every visible row",
    "copy_clear": "Clear",
    "copy_box": "Clipboard",
    # export
    "tab_export": "Export",
    "export_scope": "Scope",
    "scope_current": "Displayed image",
    "scope_all": "All loaded images",
    "export_format": "Format",
    "export_filtered": "Apply the filters from the Preview tab",
    "export_zip": "One file per image (ZIP archive)",
    "export_run": "Generate export",
    "export_file": "Generated file",
    "export_preview": "Content preview",
    # cleaning
    "tab_clean": "Remove",
    "clean_kinds": "Categories to remove",
    "clean_scope": "Scope",
    "clean_dest": "Destination",
    "dest_copy": "New file next to the original (-clean suffix)",
    "dest_dir": "Output folder",
    "dest_inplace": "Overwrite the original",
    "clean_outdir": "Output folder path",
    "clean_backup": "Create a .bak backup before overwriting",
    "clean_confirm": "I confirm overwriting the original files",
    "clean_dryrun": "Dry run (write nothing)",
    "clean_run": "Remove metadata",
    "clean_result": "Result",
    "clean_files": "Cleaned files",
    "clean_col_file": "File",
    "clean_col_removed": "Removed",
    "clean_col_before": "Before",
    "clean_col_after": "After",
    "clean_col_status": "Status",
    "clean_reencoded": "re-encoded",
    "clean_backup_note": "backup: {name}",
    # help
    "tab_help": "Help",
    # interface messages
    "msg_no_image": "No image loaded. Drop files or scan a folder.",
    "msg_loaded": "{count} image(s) analysed.",
    "msg_folder_empty": "No image found in this folder.",
    "msg_folder_missing": "Folder not found: {folder}",
    "msg_folder_blocked": "Local folder access is disabled (shared mode).",
    "msg_export_done": "Export complete: {name}",
    "msg_nothing_to_export": "Nothing to export.",
    "msg_pick_kinds": "Select at least one category to remove.",
    "msg_need_confirm": "Tick the confirmation box to overwrite the originals.",
    "msg_inplace_blocked": "Overwriting originals is disabled (shared mode or uploaded files).",
    "msg_dry_run": "Dry run: no file was modified.",
    "msg_clean_done": "{ok} file(s) cleaned, {failed} failed.",
    "msg_written_to": "Written to: {folder}",
    "msg_read_error": "Cannot read: {error}",
    # summary
    "sum_entries": "entries",
    "sum_sensitive": "sensitive",
    "sum_removable": "removable",
    "sum_dimensions": "Dimensions",
    "sum_size": "Size",
    "sum_format": "Format",
    # export documents
    "export_doc_title": "Image metadata",
    "export_generated": "Generated by ImgMetaManager on {date}",
    "export_path": "Path",
    "export_dimensions": "Dimensions",
    "export_entries": "Entries",
    "export_of_which": "including {count} sensitive",
    "export_error": "ERROR",
    "export_legend": "* = potentially identifying data",
    "export_col_tag": "Tag",
    "export_col_value": "Value",
    "export_images": "{count} image(s)",
    # core: errors, warnings and notes
    "err_not_found": "File not found: {path}",
    "err_unknown_format": "Image format not recognised by Pillow.",
    "err_no_kinds": "No metadata category selected.",
    "warn_exif_unreadable": "Unreadable EXIF: {error}",
    "warn_exif_not_rewritable": "The EXIF block could not be rewritten, so it was "
                                "removed in full.",
    "warn_reencoded": "{format} files are cleaned by re-encoding: the pixels are "
                      "recompressed and quality may change slightly.",
    "note_binary_truncated": "binary value truncated for display",
    "note_gps_decimal": "decimal coordinates computed from the DMS values",
    "note_thumbnail": "an embedded thumbnail may show the image before cropping",
    "note_xmp_unparsed": "XMP packet could not be parsed, showing the raw content",
    "note_icc": "the colour profile drives how colours render: remove it only on purpose",
    "note_app_segment": "non-standard application segment",
    "note_ai_raw": "the full graph is available in the PNG text group",
    "value_yes": "yes",
    "value_present_empty": "present but empty",
    "value_none": "—",
    "ai_a1111": "Stable Diffusion (A1111 format)",
    "ai_graph": "JSON graph ({count} entries)",
    # command line
    "cli_no_input_show": "No image file to analyse.",
    "cli_no_input_export": "No image file to export.",
    "cli_no_input_strip": "No image file to clean.",
    "cli_skipped": "Skipped (not found): {path}",
    "cli_nothing": "nothing",
    "cli_exported": "{count} image(s) exported to {path}",
    "cli_lossless": "lossless",
    "cli_reencoded": "re-encoded",
    "cli_removed": "removed",
    "cli_backup": "backup",
    "cli_port_busy": "Port {port} is already in use on {host}. "
                     "Leave --port out to pick the next free one automatically.",
    "cli_no_free_port": "No free port found between {start} and {end}. "
                        "Free one up, or pass --port with a port of your own.",
    "cli_port_auto": "Port {default} is busy, listening on {port} instead.",
    "cli_launch_failed": "The server could not start: {error}",
    # AI provenance. Wording rule: a missing signal is never evidence of
    # anything, so no string here may call an image authentic or human-made.
    "prov_section": "AI provenance",
    "prov_verdict_signals": "Provenance signals found.",
    "prov_verdict_invalid": "Provenance signals found, but they do not validate: "
                            "the file was altered after it was signed.",
    "prov_verdict_none": "No provenance signal found. This is inconclusive, "
                         "not evidence either way.",
    "prov_disclaimer": "A missing signal proves nothing: signatures and watermarks "
                       "are stripped by a screenshot, a re-encode or a metadata "
                       "cleaner, and most AI images never carried one.",
    "prov_c2pa_generator": "C2PA producer",
    "prov_c2pa_issuer": "Signed by",
    "prov_c2pa_signed_at": "Signed at",
    "prov_c2pa_source_type": "Declared source (signed)",
    "prov_c2pa_state": "Signature state",
    "prov_c2pa_error": "C2PA manifest unreadable: {error}",
    "prov_watermark": "Invisible watermark",
    "prov_watermark_found": "TrustMark payload found: {payload}",
    "prov_watermark_absent": "no TrustMark payload decoded",
    "prov_watermark_error": "Watermark decoder failed: {error}",
    "prov_declared": "Declared, unsigned",
    "prov_declared_generator": "generator metadata: {name}",
    "prov_declared_source_type": "IPTC DigitalSourceType: {value}",
    "prov_needs": "Install {package} to run this check.",
    "prov_check_watermark": "Check invisible watermark",
    "prov_watermark_hint": "Downloads a 40 MB model on first use, then takes about "
                           "a second per image. Runs only when you ask.",
    "prov_install_hint": "Install {packages} to widen the detection.",
    "prov_not_checked": "Invisible watermark not checked.",
}

FR: Dict[str, str] = {
    "app_title": "ImgMetaManager",
    "app_tagline": "Lire, exporter, copier et supprimer les métadonnées de vos images.",
    "tab_files": "Fichiers",
    "tab_folder": "Dossier",
    "upload_label": "Déposez vos images (ou cliquez pour parcourir)",
    "folder_label": "Chemin du dossier sur cette machine",
    "folder_placeholder": "/home/moi/Photos  •  C:\\Users\\moi\\Images  •  /Users/moi/Pictures",
    "folder_recursive": "Inclure les sous-dossiers",
    "folder_scan": "Analyser le dossier",
    "gallery_label": "Images analysées",
    "clear_all": "Tout retirer",
    "reload": "Ré-analyser",
    "tab_view": "Aperçu et métadonnées",
    "preview_label": "Aperçu",
    "summary_label": "Résumé",
    "filter_groups": "Groupes affichés",
    "filter_search": "Rechercher un tag ou une valeur",
    "filter_sensitive": "Uniquement les données sensibles",
    "table_group": "Groupe",
    "table_tag": "Tag",
    "table_value": "Valeur",
    "copy_section": "Copier des éléments",
    "copy_hint": "Cliquez une ligne du tableau pour l'ajouter ici, puis utilisez l'icône de copie.",
    "copy_style": "Mise en forme",
    "copy_add_all": "Ajouter toutes les lignes affichées",
    "copy_clear": "Vider",
    "copy_box": "Presse-papiers",
    "tab_export": "Exporter",
    "export_scope": "Portée",
    "scope_current": "Image affichée",
    "scope_all": "Toutes les images chargées",
    "export_format": "Format",
    "export_filtered": "Appliquer les filtres de l'onglet Aperçu",
    "export_zip": "Un fichier par image (archive ZIP)",
    "export_run": "Générer l'export",
    "export_file": "Fichier généré",
    "export_preview": "Aperçu du contenu",
    "tab_clean": "Supprimer",
    "clean_kinds": "Catégories à supprimer",
    "clean_scope": "Portée",
    "clean_dest": "Destination",
    "dest_copy": "Nouveau fichier à côté de l'original (suffixe -clean)",
    "dest_dir": "Dossier de sortie",
    "dest_inplace": "Remplacer l'original",
    "clean_outdir": "Chemin du dossier de sortie",
    "clean_backup": "Créer une sauvegarde .bak avant de remplacer",
    "clean_confirm": "Je confirme le remplacement des fichiers d'origine",
    "clean_dryrun": "Simuler (ne rien écrire)",
    "clean_run": "Supprimer les métadonnées",
    "clean_result": "Résultat",
    "clean_files": "Fichiers nettoyés",
    "clean_col_file": "Fichier",
    "clean_col_removed": "Supprimé",
    "clean_col_before": "Avant",
    "clean_col_after": "Après",
    "clean_col_status": "État",
    "clean_reencoded": "réencodé",
    "clean_backup_note": "sauvegarde : {name}",
    "tab_help": "Aide",
    "msg_no_image": "Aucune image chargée. Déposez des fichiers ou analysez un dossier.",
    "msg_loaded": "{count} image(s) analysée(s).",
    "msg_folder_empty": "Aucune image trouvée dans ce dossier.",
    "msg_folder_missing": "Dossier introuvable : {folder}",
    "msg_folder_blocked": "L'accès aux dossiers locaux est désactivé (mode partagé).",
    "msg_export_done": "Export terminé : {name}",
    "msg_nothing_to_export": "Rien à exporter.",
    "msg_pick_kinds": "Sélectionnez au moins une catégorie à supprimer.",
    "msg_need_confirm": "Cochez la case de confirmation pour remplacer les originaux.",
    "msg_inplace_blocked": "Le remplacement des originaux est désactivé (mode partagé ou "
                           "fichiers importés).",
    "msg_dry_run": "Simulation : aucun fichier n'a été modifié.",
    "msg_clean_done": "{ok} fichier(s) nettoyé(s), {failed} en échec.",
    "msg_written_to": "Enregistré dans : {folder}",
    "msg_read_error": "Lecture impossible : {error}",
    "sum_entries": "entrées",
    "sum_sensitive": "sensibles",
    "sum_removable": "supprimables",
    "sum_dimensions": "Dimensions",
    "sum_size": "Poids",
    "sum_format": "Format",
    "export_doc_title": "Métadonnées d'images",
    "export_generated": "Généré par ImgMetaManager le {date}",
    "export_path": "Chemin",
    "export_dimensions": "Dimensions",
    "export_entries": "Entrées",
    "export_of_which": "dont {count} sensibles",
    "export_error": "ERREUR",
    "export_legend": "* = donnée potentiellement identifiante",
    "export_col_tag": "Tag",
    "export_col_value": "Valeur",
    "export_images": "{count} image(s)",
    "err_not_found": "Fichier introuvable : {path}",
    "err_unknown_format": "Format d'image non reconnu par Pillow.",
    "err_no_kinds": "Aucune catégorie de métadonnée sélectionnée.",
    "warn_exif_unreadable": "EXIF illisible : {error}",
    "warn_exif_not_rewritable": "Le bloc EXIF n'a pas pu être réécrit, il a donc été "
                                "retiré en entier.",
    "warn_reencoded": "Les fichiers {format} sont nettoyés par réencodage : les pixels "
                      "sont recompressés et la qualité peut varier légèrement.",
    "note_binary_truncated": "valeur binaire tronquée à l'affichage",
    "note_gps_decimal": "coordonnées décimales calculées à partir des valeurs DMS",
    "note_thumbnail": "une miniature intégrée peut montrer l'image avant recadrage",
    "note_xmp_unparsed": "paquet XMP non analysable, contenu brut affiché",
    "note_icc": "le profil couleur pilote le rendu : ne le supprimez qu'en connaissance de cause",
    "note_app_segment": "segment applicatif non standard",
    "note_ai_raw": "le graphe complet est disponible dans le groupe Texte PNG",
    "value_yes": "oui",
    "value_present_empty": "présent mais vide",
    "value_none": "—",
    "ai_a1111": "Stable Diffusion (format A1111)",
    "ai_graph": "graphe JSON ({count} entrées)",
    "cli_no_input_show": "Aucun fichier image à analyser.",
    "cli_no_input_export": "Aucun fichier image à exporter.",
    "cli_no_input_strip": "Aucun fichier image à nettoyer.",
    "cli_skipped": "Ignoré (introuvable) : {path}",
    "cli_nothing": "rien",
    "cli_exported": "{count} image(s) exportée(s) vers {path}",
    "cli_lossless": "sans perte",
    "cli_reencoded": "réencodé",
    "cli_removed": "supprimé",
    "cli_backup": "sauvegarde",
    "cli_port_busy": "Le port {port} est déjà utilisé sur {host}. "
                     "Omettez --port pour prendre automatiquement le suivant libre.",
    "cli_no_free_port": "Aucun port libre entre {start} et {end}. "
                        "Libérez-en un, ou indiquez le vôtre avec --port.",
    "cli_port_auto": "Le port {default} est occupé, écoute sur le port {port}.",
    "cli_launch_failed": "Le serveur n'a pas pu démarrer : {error}",
    "prov_section": "Provenance IA",
    "prov_verdict_signals": "Signaux de provenance trouvés.",
    "prov_verdict_invalid": "Signaux de provenance trouvés, mais ils ne se valident "
                            "pas : le fichier a été modifié après sa signature.",
    "prov_verdict_none": "Aucun signal de provenance trouvé. Ce résultat n'est pas "
                         "concluant, ni dans un sens ni dans l'autre.",
    "prov_disclaimer": "Une absence de signal ne prouve rien : une capture d'écran, "
                       "un réencodage ou un nettoyage de métadonnées effacent "
                       "signatures et filigranes, et la plupart des images générées "
                       "n'en ont jamais porté.",
    "prov_c2pa_generator": "Producteur C2PA",
    "prov_c2pa_issuer": "Signé par",
    "prov_c2pa_signed_at": "Signé le",
    "prov_c2pa_source_type": "Source déclarée (signée)",
    "prov_c2pa_state": "État de la signature",
    "prov_c2pa_error": "Manifeste C2PA illisible : {error}",
    "prov_watermark": "Filigrane invisible",
    "prov_watermark_found": "charge utile TrustMark trouvée : {payload}",
    "prov_watermark_absent": "aucune charge utile TrustMark décodée",
    "prov_watermark_error": "Le décodeur de filigrane a échoué : {error}",
    "prov_declared": "Déclaratif, non signé",
    "prov_declared_generator": "métadonnées de génération : {name}",
    "prov_declared_source_type": "IPTC DigitalSourceType : {value}",
    "prov_needs": "Installez {package} pour effectuer cette vérification.",
    "prov_check_watermark": "Vérifier le filigrane invisible",
    "prov_watermark_hint": "Télécharge un modèle de 40 Mo au premier usage, puis "
                           "prend environ une seconde par image. Ne s'exécute que "
                           "sur demande.",
    "prov_install_hint": "Installez {packages} pour élargir la détection.",
    "prov_not_checked": "Filigrane invisible non vérifié.",
}

#: Group labels, keyed by ``group_<key>``.
_GROUPS_EN = {
    "group_file": "File",
    "group_image": "Image",
    "group_exif": "EXIF",
    "group_gps": "GPS / Location",
    "group_iptc": "IPTC",
    "group_xmp": "XMP",
    "group_png_text": "PNG text",
    "group_comment": "Comments",
    "group_icc": "ICC profile",
    "group_thumbnail": "Embedded thumbnail",
    "group_ai": "Generative AI",
    "group_other": "Other",
}
_GROUPS_FR = {
    "group_file": "Fichier",
    "group_image": "Image",
    "group_exif": "EXIF",
    "group_gps": "GPS / Localisation",
    "group_iptc": "IPTC",
    "group_xmp": "XMP",
    "group_png_text": "Texte PNG",
    "group_comment": "Commentaires",
    "group_icc": "Profil ICC",
    "group_thumbnail": "Miniature intégrée",
    "group_ai": "IA générative",
    "group_other": "Divers",
}
EN.update(_GROUPS_EN)
FR.update(_GROUPS_FR)

LANGUAGES = {"en": EN, "fr": FR}
DEFAULT_LANGUAGE = "en"

_current = DEFAULT_LANGUAGE


def detect_language(fallback: str = DEFAULT_LANGUAGE) -> str:
    """Guess the interface language from the environment.

    Reads ``IMM_LANG`` first, then the usual POSIX locale variables, then the
    system locale. Any locale the project does not translate falls back to
    English.
    """
    for variable in ("IMM_LANG", "LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"):
        raw = os.environ.get(variable)
        if not raw:
            continue
        code = raw.split(":")[0].split(".")[0].split("_")[0].strip().lower()
        if code in LANGUAGES:
            return code
        if code and code not in ("c", "posix"):
            return fallback
    try:  # Windows has no LANG variable; ask the C library instead.
        import locale

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            system = (locale.getdefaultlocale()[0] or "")
        code = system.split("_")[0].strip().lower()
        if code in LANGUAGES:
            return code
    except Exception:  # noqa: BLE001 - locale lookups fail on exotic systems
        pass
    return fallback


def set_language(code: str) -> str:
    """Select the active language and return the code actually applied."""
    global _current
    _current = code if code in LANGUAGES else DEFAULT_LANGUAGE
    return _current


def current_language() -> str:
    """Return the active language code."""
    return _current


def t(key: str, **kwargs: object) -> str:
    """Translate ``key``, falling back to English then to the key itself.

    Keyword arguments are substituted into the string; a formatting mismatch
    returns the unformatted text rather than raising.
    """
    text = LANGUAGES.get(_current, EN).get(key) or EN.get(key) or key
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, IndexError):
            return text
    return text


def group_label(key: str) -> str:
    """Return the display label of a metadata group."""
    return t(f"group_{key}")


def colon() -> str:
    """Return the label separator, with the narrow space French typography wants."""
    return "\u00a0: " if _current == "fr" else ": "


HELP_EN = """
### What this application does

1. **Read**: image preview plus a full inventory of the metadata, covering
   EXIF, GPS, IPTC, XMP, PNG text chunks, comments, ICC profile, embedded
   thumbnail and the settings of image generators (Stable Diffusion, ComfyUI).
2. **Export**: JSON, CSV, TXT, Markdown or HTML, for one image or the whole batch.
3. **Copy**: click table rows, then use the copy icon (`Tag = value`, TSV for
   spreadsheets, JSON, or values only).
4. **Remove**: by category or all at once.

### Lossless removal

For **JPEG**, **PNG** and **WebP**, metadata is stripped at the container level:
the compressed pixels are copied byte for byte, with no re-encoding and no
quality loss. Other formats (TIFF, GIF, BMP, HEIC and so on) go through a
re-encode, flagged with ♻️ in the report.

**Remove everything** spares the **ICC profile**, which drives how colours
render. Tick it explicitly if you really want it gone. Removing **EXIF** also
removes **GPS** and the **thumbnail**: they live in the same block.

### File safety

- By default a new `name-clean.ext` file is written and the original is untouched.
- Overwriting the original needs an explicit confirmation and writes a `.bak` backup.
- {local_note}

### Sensitive data

Entries marked ⚠ (GPS, serial numbers, author names, MakerNote, places) are the
ones that identify a person, a place or a device. The "Sensitive data only"
filter isolates them in one click.

### AI provenance

Three independent signals are looked for, in the context of article 50 of the
EU AI Act:

1. A **C2PA manifest**, cryptographically signed, naming the tool that produced
   the file and the certificate that signed it.
2. An **invisible TrustMark watermark** carried by the pixels, which survives
   resizing and re-encoding. It loads a model, so it runs only when you press
   the button.
3. **Declarative metadata**: generator parameters and the IPTC
   `DigitalSourceType` field. Plain text, which anyone can write or erase.

**Read the result carefully.** A found signal tells you something about the
file's history. An absent signal tells you nothing at all: a screenshot, a
re-encode or a metadata cleaner removes every one of them, and most AI images
never carried any. This application therefore never labels an image as
authentic, and never states that an image is not AI-generated. The three
possible outcomes are: signals found, signals found but invalid, and no signal,
which is inconclusive.

### Readable formats

{formats}

*HEIC/HEIF and AVIF need the optional `pillow-heif` package.*
"""

HELP_FR = """
### Ce que fait cette application

1. **Lire** : aperçu de l'image et inventaire complet des métadonnées, soit EXIF,
   GPS, IPTC, XMP, chunks texte PNG, commentaires, profil ICC, miniature intégrée
   et paramètres des générateurs d'images (Stable Diffusion, ComfyUI).
2. **Exporter** : JSON, CSV, TXT, Markdown ou HTML, pour une image ou pour tout le lot.
3. **Copier** : cliquez les lignes du tableau puis utilisez l'icône de copie
   (`Tag = valeur`, TSV pour tableur, JSON, ou valeurs seules).
4. **Supprimer** : par catégorie ou en totalité.

### Suppression sans perte

Pour le **JPEG**, le **PNG** et le **WebP**, les métadonnées sont retirées au niveau
des segments du fichier : les pixels compressés sont recopiés à l'identique,
sans réencodage ni perte de qualité. Les autres formats (TIFF, GIF, BMP, HEIC…)
passent par un réencodage, signalé par l'icône ♻️ dans le rapport.

Le **profil ICC** n'est jamais supprimé par « tout supprimer » : il pilote le rendu
des couleurs. Cochez-le explicitement si vous voulez vraiment le retirer.
Supprimer l'**EXIF** entraîne la suppression du **GPS** et de la **miniature**, qui
sont stockés dans le même bloc.

### Sécurité des fichiers

- Par défaut, un nouveau fichier `nom-clean.ext` est créé : l'original n'est pas touché.
- Le remplacement de l'original demande une confirmation explicite et crée
  une sauvegarde `.bak`.
- {local_note}

### Données sensibles

Les entrées marquées ⚠ (GPS, numéros de série, noms d'auteur, MakerNote, lieux)
sont celles qui permettent d'identifier une personne, un lieu ou un appareil.
Le filtre « Uniquement les données sensibles » les isole en un clic.

### Provenance IA

Trois signaux indépendants sont recherchés, dans le cadre de l'article 50 du
règlement européen sur l'IA :

1. Un **manifeste C2PA**, signé cryptographiquement, qui nomme l'outil ayant
   produit le fichier et le certificat qui l'a signé.
2. Un **filigrane invisible TrustMark** porté par les pixels, qui survit à un
   redimensionnement et à un réencodage. Il charge un modèle, donc il ne
   s'exécute qu'au clic sur le bouton.
3. Les **métadonnées déclaratives** : paramètres de génération et champ IPTC
   `DigitalSourceType`. Du texte simple, que n'importe qui peut écrire ou effacer.

**Lisez le résultat avec précaution.** Un signal trouvé renseigne sur
l'histoire du fichier. Un signal absent ne renseigne sur rien : une capture
d'écran, un réencodage ou un nettoyage de métadonnées les efface tous, et la
plupart des images générées n'en ont jamais porté. Cette application ne qualifie
donc jamais une image d'authentique, et n'affirme jamais qu'une image n'est pas
générée. Trois résultats sont possibles : signaux trouvés, signaux trouvés mais
invalides, et aucun signal, ce qui n'est pas concluant.

### Formats lus

{formats}

*HEIC/HEIF et AVIF nécessitent le paquet optionnel `pillow-heif`.*
"""

LOCAL_NOTE_EN = {
    True: "The **Folder** tab reads images straight from this machine: that is the "
          "mode to use when replacing the original files.",
    False: "Local folder access is **disabled** (the application runs in shared mode).",
}
LOCAL_NOTE_FR = {
    True: "L'onglet **Dossier** lit les images directement sur cette machine : "
          "c'est le mode à utiliser pour remplacer les fichiers d'origine.",
    False: "L'accès aux dossiers locaux est **désactivé** (application lancée en "
           "mode partagé).",
}


def help_text(allow_local: bool, formats: str) -> str:
    """Render the Help tab for the active language."""
    if _current == "fr":
        return HELP_FR.format(local_note=LOCAL_NOTE_FR[bool(allow_local)], formats=formats)
    return HELP_EN.format(local_note=LOCAL_NOTE_EN[bool(allow_local)], formats=formats)
